version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo "test0"

  pre_build:
    commands:
      - echo "test1"

  build:
      - echo "test2"

  post_build:
    commands:
      - echo "test3"
